color0 #121410
color1 #ffb4ab
color2 #a0d57b
color3 #bdcbaf
color4 #a0cfce
color5 #a0d57b
color6 #bdcbaf
color7 #e3e3dc
color8 #8e9286
color9 #ffb4ab
color10 #a0d57b
color11 #bdcbaf
color12 #a0cfce
color13 #a0d57b
color14 #bdcbaf
color15 #e3e3dc

cursor                #e3e3dc
cursor_text_color     #121410
background            #121410
foreground            #e3e3dc
selection_foreground  #c4c8bb
selection_background  #43483e
active_border_color   #a0d57b
inactive_border_color #43483e
url_color             #a0d57b

active_tab_foreground   #163800
active_tab_background   #a0d57b
inactive_tab_foreground #c4c8bb
inactive_tab_background #43483e
cursor_trail_color      #c4c8bb
